name: pyds
channels:
  - conda-forge
dependencies:
  # Core stack
  - python=3.10
  - pip
  - build
  - twine
  - jupyter
  - jupyterlab
  - ipykernel
  - jinja2
  - loguru
  - pyprojroot
  - ruamel.yaml # allows preserving of EOL comments.
  # CLI development
  - typer
  - cookiecutter
  # Software testing
  - pytest
  - hypothesis
  - pytest-cov
  # Code Style Tools
  - pre-commit
  - black
  - darglint
  - interrogate
  - flake8
  - bump2version
  # Documentation
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  # pip dependencies
  - pip:
      - mknotebooks
      - typer-cli
      - case-converter
      - rich
      - jinja2-strcase
