name: pyds
channels:
- conda-forge
dependencies:
# Core stack
- python=3.9
- pip
- build
- twine
- jupyter
- jupyterlab
- ipykernel
- mamba
- jinja2
# Standard PyData stack
- pandas
- matplotlib
- numpy
- scipy
- seaborn
- pymc3
- scikit-learn
# CLI development
- typer
# Software testing
- pytest
- hypothesis
# Code Style Tools
- pre-commit
- black
- darglint
- interrogate
- flake8
# Documentation
- mkdocs
- mkdocs-material
- mkdocstrings
# pip dependencies
- pip:
  - mknotebooks
