name: {{ cookiecutter.__conda_env_name }}
channels:
- conda-forge
dependencies:
# Core stack
- python=3.10
- build
- bump2version
- ipykernel
- ipywidgets
- jupyter
- jupyterlab
- pip
- twine
# Standard PyData stack
- matplotlib
- numpy
- pandas
- pymc
- scikit-learn
- scipy
- seaborn
- statsmodels
# Utilities
- pyprojroot
- python-dotenv
# CLI development
- typer
- typer-cli
# Software testing
- hypothesis
- pytest
- pytest-cov
- coverage
# Code Style Tools
- black
- darglint
- flake8
- interrogate
- pre-commit
- pylint
# Documentation
- mkdocs
- mkdocs-material
- mkdocstrings
# pip dependencies
- pip:
  # Place packages that cannot be installed by conda in this section.
  - mknotebooks
