repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ericmjl/webp-pre-commit
    rev: v0.0.8
    hooks:
      - id: convert-to-webp
