name: Build documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    name: Build documentation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          environments: docs

      - name: Build docs
        run: |
          pixi run cli-docs
          pixi run build-docs

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-personal-access-token-personal_token
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages
          # destination_dir: manuscript
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
          enable_jekyll: false
