name: Run tests on pull requests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pixi-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Run test suite within pixi environment (${{ matrix.os }})

    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          environments: testing

      - name: Run tests
        run: |
          git config --global user.name "GitHub Tester"
          git config --global user.email "github@tester.com"

          pixi run test

  # This helps us check that pyproject.toml's `project` table's `dependencies`
  # are defined completely.
  bare-install:
    runs-on: ubuntu-latest
    name: Run bare installation test

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run pyds-cli
        run: |
          pyds --help
