name: Run tests on pull requests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pixi-tests:
    runs-on: ubuntu-latest
    name: Run test suite within pixi environment

    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: 'latest'
          environment-file: environment.yml
          init-shell: bash
          cache-environment: true
          cache-environment-key: environment-${{ steps.date.outputs.date }}
          cache-downloads-key: downloads-${{ steps.date.outputs.date }}
          post-cleanup: 'all'

      - name: Run tests
        run: |
          pip install -e .
          pytest

  # This helps us check that pyproject.toml's `project` table's `dependencies`
  # are defined completely.
  bare-install:
    runs-on: ubuntu-latest
    name: Run bare installation test

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run pyds-cli
        run: |
          pyds --help
