name: Run tests on pull requests

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  build-environment:
    runs-on: ubuntu-latest
    name: Run test suite

    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.4.5-0'
          environment-file: environment.yml
          init-shell: bash
          cache-environment: true
          cache-environment-key: environment-${{ steps.date.outputs.date }}
          cache-downloads-key: downloads-${{ steps.date.outputs.date }}
          post-cleanup: 'all'

      - name: Run tests
        run: |
          conda activate pyds
          pip install -e .
          pytest
